INSERT INTO TB_PIVOT VALUES (							'2023'	,	1		);
INSERT INTO TB_PIVOT VALUES (							'2023'	,	2		);
INSERT INTO TB_PIVOT VALUES (							'2023'	,	3		);
INSERT INTO TB_PIVOT VALUES (							'2023'	,	4		);
INSERT INTO TB_PIVOT VALUES (							'2023'	,	5		);
INSERT INTO TB_PIVOT VALUES (							'2023'	,	6		);
INSERT INTO TB_PIVOT VALUES (							'2023'	,	7		);
INSERT INTO TB_PIVOT VALUES (							'2023'	,	8		);
INSERT INTO TB_PIVOT VALUES (							'2023'	,	9		);
INSERT INTO TB_PIVOT VALUES (							'2023'	,	10		);
INSERT INTO TB_PIVOT VALUES (							'2023'	,	11		);
INSERT INTO TB_PIVOT VALUES (							'2023'	,	12		);

COMMIT;
-- DELETE FROM TB_PIVOT; 테이블 제거
-- SELECT * FROM TB_PIVOT; 